/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 11:17:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.UTC.dto.MemberDto;

public final class my_005fpage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/usertopbar.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KH_semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/inc/footer_my_page.jsp", Long.valueOf(1566187849000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.UTC.dto.MemberDto");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("<title>UTC</title>\r\n");
      out.write("\t");

	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-control", "no-store");
	response.setHeader("Expires", "0");
	//세션 삭제 코드

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>UTC</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"plugins/handlebars/handlebars-v4.0.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!--  드롭다운-->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-link\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\n");
      out.write("    \t\t<div class=\"dropdown-menu\">     \t\t\r\n");
      out.write("    \t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=make_up_self\"><strong style=\"color:dark;\">Create My Page</strong></a>\r\n");
      out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=list\" class=\"is-current\">User Reviews</a>\r\n");
      out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=qalist\">Q&nbsp;&&nbsp;A Board</a>\r\n");
      out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=ntlist\">Notice</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=mypage\"><strong style=\"color:dark;\">My page</strong></a>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 드롭다운 종료 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 버튼 -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"user_main.jsp\">UTC</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t<!-- 화면줄이면 나오는 버튼 -->\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><li class=\"nav-item\"><a class=\"nav-link\" style=\"color: white;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 환영합니다!</a></li>\r\n");
      out.write("               <li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"SemiProjectServlet.do?command=logout\">Logout</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal 1 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal3\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal 2 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<!-- loginform.jsp가 연결된다. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Modal 3 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal2\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<!-- signup.jsp 연결(회원정보수정) -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/** 모달 창이 닫히는 경우의 이벤트 */\r\n");
      out.write("\t\t// \".modal\"로 지정할 경우 : 모든 모달창에 적용됨\r\n");
      out.write("\t\t// \"#아이디\"로 지정할 경우 : 특정 모달 창에 적용\r\n");
      out.write("\t\t$('.modal').on('hidden.bs.modal', function(e) {\r\n");
      out.write("\t\t\t// 모달창 내의 내용을 강제로 지움.\r\n");
      out.write("\t\t\t$(this).removeData('bs.modal');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<link href=\"css/index_menu.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"dist/jquery.flipster.min.css\">\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"plugins/ajax/ajax_helper.css\" />\r\n");
      out.write("\r\n");
      out.write("\t<script src=\"dist/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"dist/jquery.flipster.min.js\"></script>\r\n");
      out.write("\t<script src=\"plugins/handlebars-v4.0.5.js\"></script>\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"https://code.jquery.com/jquery-3.3.1.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("/* 사이드메뉴클릭시 div에 내용 표시 */\r\n");
      out.write("$(document).ready(function() {\r\n");
      out.write("/* \tmypage 처음 로딩 시 mine.jsp를 불러온다 */\r\n");
      out.write("\t$(\"#target\").load(\"SemiProjectServlet.do?command=listOfuser\").trigger(\"click\");\r\n");
      out.write("\r\n");
      out.write("/* 마이페이지 클릭했을 때 */\r\n");
      out.write("\t$(\"#load_mine\").on(\"click\",function(){\r\n");
      out.write("\t\t$(\"#target\").load(\"SemiProjectServlet.do?command=listOfuser\");\r\n");
      out.write("\t});\r\n");
      out.write("\r\n");
      out.write("/* 내가만든페이지 클릭했을 때 */\r\n");
      out.write("/* \t$(\"#load_locker\").on(\"click\",function(){\r\n");
      out.write("\t\t$(\"#target\").load(\"SemiProjectServlet.do?command=iMadeUser\");\r\n");
      out.write("\t}); */\r\n");
      out.write("\r\n");
      out.write("});\r\n");
      out.write("\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style>\r\n");
      out.write("@import\r\n");
      out.write("\turl('http://fonts.googleapis.com/css?family=Open+Sans:300,400,700');\r\n");
      out.write("\r\n");
      out.write("@import\r\n");
      out.write("\turl('http://netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css')\r\n");
      out.write("\t;\r\n");
      out.write("\r\n");
      out.write("body {\r\n");
      out.write("\tcolor: #5D5F63;\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tfont-family: 'Open Sans', sans-serif;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\ttext-rendering: optimizeLegibility;\r\n");
      out.write("\t-webkit-font-smoothing: antialiased;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar {\r\n");
      out.write("\twidth: 15%;\r\n");
      out.write("/*  \theight:70%;  */\r\n");
      out.write("\tbackground: white;\r\n");
      out.write("\tposition: fixed;\r\n");
      out.write("\tdisplay: inherit;\r\n");
      out.write("\t-webkit-transition: all 0.3s ease-in-out;\r\n");
      out.write("\t-moz-transition: all 0.3s ease-in-out;\r\n");
      out.write("\t-o-transition: all 0.3s ease-in-out;\r\n");
      out.write("\t-ms-transition: all 0.3s ease-in-out;\r\n");
      out.write("\ttransition: all 0.3s ease-in-out;\r\n");
      out.write("\tz-index: 100;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar #leftside-navigation ul, .sidebar #leftside-navigation ul ul {\r\n");
      out.write("\tmargin: -2px 0 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar #leftside-navigation ul li {\r\n");
      out.write("\tlist-style-type: none;\r\n");
      out.write("\tborder-bottom: 1px solid rgba(255, 255, 255, 0.05);\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar #leftside-navigation ul li.active ul {\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar #leftside-navigation ul li a {\r\n");
      out.write("\tcolor: black;\r\n");
      out.write("\ttext-decoration: none;\r\n");
      out.write("\tdisplay: block;\r\n");
      out.write("\tpadding: 18px 0 18px 25px;\r\n");
      out.write("\tfont-size: 12px;\r\n");
      out.write("\toutline: 0;\r\n");
      out.write("\t-webkit-transition: all 200ms ease-in;\r\n");
      out.write("\t-moz-transition: all 200ms ease-in;\r\n");
      out.write("\t-o-transition: all 200ms ease-in;\r\n");
      out.write("\t-ms-transition: all 200ms ease-in;\r\n");
      out.write("\ttransition: all 200ms ease-in;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar #leftside-navigation ul li a:hover {\r\n");
      out.write("\tcolor: silver;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar #leftside-navigation ul li a span {\r\n");
      out.write("\tdisplay: inline-block;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".sidebar #leftside-navigation ul li a i {\r\n");
      out.write("\twidth: 20px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("section {\r\n");
      out.write("\theight: 400px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#left {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("#right {\r\n");
      out.write("\twidth: 85%;\r\n");
      out.write("\theight: 100%;\r\n");
      out.write("\tfloat: right;\r\n");
      out.write("\tmargin-bottom: 150px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");

System.out.println("세션 정보 확인");
//로그인 값 가져오기
MemberDto logindto = (MemberDto)session.getAttribute("dto");
System.out.println("세션이메일: "+ logindto.getMember_email());
System.out.println("회원번호: "+ logindto.getMember_id());

      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<br>\r\n");
      out.write("\t<aside class=\"sidebar\" id=\"left\">\r\n");
      out.write("\t\t<div id=\"leftside-navigation\" class=\"nano\">\r\n");
      out.write("\t\t\t<ul class=\"nano-content\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<li class=\"nano-content\"><a href=\"#\" id=\"load_mine\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-table\"></i><span>마이페이지</span><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"arrow fa fa-angle-right pull-right\"></i></a></li>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<!-- <li class=\"nano-content\"><a href=\"#\" id=\"load_locker\"><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"fa fa-table\"></i><span>내가 만든 페이지</span><i\r\n");
      out.write("\t\t\t\t\t\tclass=\"arrow fa fa-angle-right pull-right\"></i></a></li> -->\r\n");
      out.write("\t\t\t</ul>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</aside>\r\n");
      out.write("\r\n");
      out.write("\t<article class=\"html5\" id=\"right\">\r\n");
      out.write("\t<div id=\"target\">\r\n");
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("\t</article>\r\n");
      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".footer{\r\n");
      out.write("position : fixed;\r\n");
      out.write("left: 0;\r\n");
      out.write("bottom: 0%;\r\n");
      out.write("width: 100%;\r\n");
      out.write("background-color: black;\r\n");
      out.write("opacity: 0.8;\r\n");
      out.write("color: silver;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size: small;\r\n");
      out.write("#4c4c4c; \r\n");
      out.write("height: 110px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      <div class=\"footer\">\r\n");
      out.write("         <p>Copyright &copy; ;&nbsp;&nbsp;&nbsp;Website 2018</p>\r\n");
      out.write("         <p>제작자 : 김동민 박우주 성원실 전성은 최강일 최경수</p>\r\n");
      out.write("         <p>제작 일자&nbsp; 2018-12-12</p>\r\n");
      out.write("      </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Bootstrap core JavaScript -->\r\n");
      out.write("   <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
