/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 10:42:01 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.UTC.dto.MemberDto;

public final class qa_005fupdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(5);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/usertopbar.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/footer.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KH_semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/inc/topbar.jsp", Long.valueOf(1566187849000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.UTC.dto.MemberDto");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("\n");
      out.write("    \n");

    String ctx = request.getContextPath();    //콘텍스트명 얻어오기.
	MemberDto dto = (MemberDto)session.getAttribute("dto");

      out.write("\n");
      out.write("<!-- C태그 사용 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<title>UTC</title>\n");
      out.write("<!-- 로그인정보가 있으면 usertopbar 없으면 topbar를 띄움 -->\n");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /qa_update.jsp(16,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\n');
            out.write('	');
            out.write("\r\n");
            out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
            out.write('\r');
            out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
            out.write(" \r\n");
            out.write("<!DOCTYPE html>\r\n");
            out.write("<html>\r\n");
            out.write("\t<head>\r\n");
            out.write("\t<meta charset=\"utf-8\">\r\n");
            out.write("\t<title>UTC</title>\r\n");
            out.write("\t\r\n");
            out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
            out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
            out.write("<script src=\"plugins/handlebars/handlebars-v4.0.5.js\"></script>\r\n");
            out.write("\r\n");
            out.write("<!-- 입력값 유효성 검사 스크립트 -->\r\n");
            out.write("<script type=\"text/javascript\">\r\n");
            out.write("\r\n");
            out.write("//회원가입 폼 비밀번호 유효성 검사\r\n");
            out.write("function pw_check(){\r\n");
            out.write("\t\r\n");
            out.write("\t//패스워드 유효성 체크(문자,숫자,특수문자의 조합으로 6~16자리로)\r\n");
            out.write("\tvar userPw = document.joinform.member_pw;\r\n");
            out.write("\tvar userPwRe = document.joinform.member_pw_re;\r\n");
            out.write("\t\r\n");
            out.write("\t//비밀번호가 같은지 검사\r\n");
            out.write("\tif(userPw.value != userPwRe.value){\r\n");
            out.write("\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
            out.write("\t\treturn false;\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t//비밀번호 6자리 미만이면 알림\r\n");
            out.write("\tif(userPw.value.length < 6){\r\n");
            out.write("\t\talert(\"비밀번호는 6자리 이상으로 만들어주세요.\");\r\n");
            out.write("\t\treturn false;\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t//비밀번호 생성시 특수문자 섞어서 만들기\r\n");
            out.write("\tif(!userPw.value.match(/([a-zA-Z0-9].*[!,@,#,$,%,^,&,*,?,_,~])|([!,@,#,$,%,^,&,*,?,_,~].*[a-zA-Z0-9])/)){\r\n");
            out.write("\t\talert(\"비밀번호는 특수문자(!@$%^&* 만 허용)를 섞어서 6자리 이상으로 만들어주세요.\");\r\n");
            out.write("\t\treturn false;\r\n");
            out.write("\t}\r\n");
            out.write("\treturn true;\r\n");
            out.write("}\r\n");
            out.write("\r\n");
            out.write("//회원가입 폼 이메일 유효성 검사하기(이메일 형식 검사)\r\n");
            out.write("function email_check(){\r\n");
            out.write("\tvar email = document.getElementById(\"inputEmail\").value;\r\n");
            out.write("\tvar chk_list = /^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/;\r\n");
            out.write("\t\tif(chk_list.test(email)==false){\r\n");
            out.write("\t\t\talert(\"이메일 형식이 올바르지 않습니다.\");\r\n");
            out.write("\t\t\tdocument.joinform.email.focus();\r\n");
            out.write("\t\t\treturn false;\r\n");
            out.write("\t\t}\r\n");
            out.write("}\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</script>\r\n");
            out.write("</head>\r\n");
            out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
            out.write("<body>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Navigation -->\r\n");
            out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<!--  드롭다운-->\r\n");
            out.write("\t<div class=\"container\">\r\n");
            out.write(" \t\t<div class=\"dropdown\">\r\n");
            out.write("    \t\t<button type=\"button\" class=\"btn btn-link\" data-toggle=\"dropdown\">\r\n");
            out.write("      \t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("   \t\t\t</button>\r\n");
            out.write("   \t\t\t\r\n");
            out.write("    \t\t<div class=\"dropdown-menu\">     \t\t\r\n");
            out.write("    \t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=make_up_self\"><strong style=\"color:dark;\">Create My Page</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=list\"><strong style=\"color:dark;\">User Reviews</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=qalist\"><strong style=\"color:dark;\">Q&nbsp;&&nbsp;A Board</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=ntlist\"><strong style=\"color:dark;\">Notice</strong></a>\r\n");
            out.write("\t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=mypage\"><strong style=\"color:dark;\">My page</strong></a>\r\n");
            out.write("    \t\t</div>\r\n");
            out.write("  \t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t<!-- 드롭다운 종료 -->\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<!-- 버튼 -->\n");
            out.write("\t<div class=\"container\">\r\n");
            out.write("\t\t<a class=\"navbar-brand\" href=\"index.jsp\">UTC</a>\r\n");
            out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
            out.write("            \t<span class=\"navbar-toggler-icon\"></span>\t\t<!-- 화면줄이면 나오는 버튼 -->\r\n");
            out.write("         \t</button>\r\n");
            out.write("         \t\r\n");
            out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
            out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
            out.write("\t\t\t\t\t\t<a id=\"modalButton\" class=\"nav-link\" href=\"loginform.jsp\" data-toggle=\"modal\" data-target=\"#myModal\">Login</a>\n");
            out.write("\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
            out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"signup.jsp\" data-toggle=\"modal\" data-target=\"#myModal2\">SignUp</a>\r\n");
            out.write("\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t</ul>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("</nav>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 1 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal3\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 2 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
            out.write(" \t<div class=\"modal-dialog modal-md\">\t\t\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- loginform.jsp가 연결된다. -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t\r\n");
            out.write("\t<!-- Modal 3 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal2\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- signup.jsp 연결(회원정보수정) -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<script type=\"text/javascript\">\r\n");
            out.write("\t\t/** 모달 창이 닫히는 경우의 이벤트 */\r\n");
            out.write("\t\t// \".modal\"로 지정할 경우 : 모든 모달창에 적용됨\r\n");
            out.write("\t\t// \"#아이디\"로 지정할 경우 : 특정 모달 창에 적용\r\n");
            out.write("\t\t$('.modal').on('hidden.bs.modal', function(e) {\r\n");
            out.write("\t\t\t//모달창 내의 내용을 강제로 지움.\r\n");
            out.write("\t\t\t//밑에꺼 안되서 바꿈\r\n");
            out.write("\t\t\t$(this).find('form')[0].reset()\r\n");
            out.write("\t\t\t//$(this).removeData('bs.modal');\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t});\r\n");
            out.write("\t</script>\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write('\n');
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /qa_update.jsp(19,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\n');
            out.write('	');

	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-control", "no-store");
	response.setHeader("Expires", "0");
	//세션 삭제 코드

            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
            out.write('\r');
            out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\r\n");
            out.write("<!DOCTYPE html>\r\n");
            out.write("<html>\r\n");
            out.write("\r\n");
            out.write("<head>\r\n");
            out.write("<meta charset=\"utf-8\">\r\n");
            out.write("<title>UTC</title>\r\n");
            out.write("\r\n");
            out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
            out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
            out.write("<script src=\"plugins/handlebars/handlebars-v4.0.5.js\"></script>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</head>\r\n");
            out.write("\r\n");
            out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
            out.write("<body>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Navigation -->\r\n");
            out.write("\t<nav\r\n");
            out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t<!--  드롭다운-->\r\n");
            out.write("\t\t<div class=\"container\">\r\n");
            out.write("\t\t\t<div class=\"dropdown\">\r\n");
            out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-link\" data-toggle=\"dropdown\">\r\n");
            out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("\t\t\t\t</button>\r\n");
            out.write("\n");
            out.write("    \t\t<div class=\"dropdown-menu\">     \t\t\r\n");
            out.write("    \t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=make_up_self\"><strong style=\"color:dark;\">Create My Page</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=list\" class=\"is-current\">User Reviews</a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=qalist\">Q&nbsp;&&nbsp;A Board</a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=ntlist\">Notice</a>\r\n");
            out.write("\t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=mypage\"><strong style=\"color:dark;\">My page</strong></a>\r\n");
            out.write("    \t\t</div>\r\n");
            out.write("\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t\t<!-- 드롭다운 종료 -->\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t<!-- 버튼 -->\r\n");
            out.write("\t\t<div class=\"container\">\r\n");
            out.write("\t\t\t<a class=\"navbar-brand\" href=\"user_main.jsp\">UTC</a>\r\n");
            out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
            out.write("\t\t\t\tdata-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
            out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
            out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("\t\t\t\t<!-- 화면줄이면 나오는 버튼 -->\r\n");
            out.write("\t\t\t</button>\r\n");
            out.write("\r\n");
            out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
            out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\"><li class=\"nav-item\"><a class=\"nav-link\" style=\"color: white;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("님 환영합니다!</a></li>\r\n");
            out.write("               <li class=\"nav-item\"><a class=\"nav-link\"\r\n");
            out.write("\t\t\t\t\t\thref=\"SemiProjectServlet.do?command=logout\">Logout</a>\r\n");
            out.write("\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t</ul>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("</nav>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 1 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal3\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 2 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- loginform.jsp가 연결된다. -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t\r\n");
            out.write("\t<!-- Modal 3 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal2\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- signup.jsp 연결(회원정보수정) -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<script type=\"text/javascript\">\r\n");
            out.write("\t\t/** 모달 창이 닫히는 경우의 이벤트 */\r\n");
            out.write("\t\t// \".modal\"로 지정할 경우 : 모든 모달창에 적용됨\r\n");
            out.write("\t\t// \"#아이디\"로 지정할 경우 : 특정 모달 창에 적용\r\n");
            out.write("\t\t$('.modal').on('hidden.bs.modal', function(e) {\r\n");
            out.write("\t\t\t// 모달창 내의 내용을 강제로 지움.\r\n");
            out.write("\t\t\t$(this).removeData('bs.modal');\r\n");
            out.write("\t\t});\r\n");
            out.write("\t</script>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write("\n");
      out.write("\n");
      out.write("<!-- SmartEditor를 사용하기 위해서 다음 js파일을 추가 (경로 확인) -->\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(ctx );
      out.write("/SE2/js/HuskyEZCreator.js\" charset=\"utf-8\"></script>\n");
      out.write("\n");
      out.write("<!-- ReviewWrite css 참조 -->\n");
      out.write("<link href=\"css/ReviewWrite.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/index_menu.css\" rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("var oEditors = [];\n");
      out.write("$(function(){\n");
      out.write("      nhn.husky.EZCreator.createInIFrame({\n");
      out.write("          oAppRef: oEditors,\n");
      out.write("          elPlaceHolder: \"ir1\", //textarea에서 지정한 id와 일치해야 합니다. \n");
      out.write("          //SmartEditor2Skin.html 파일이 존재하는 경로\n");
      out.write("          sSkinURI: \"SE2/SmartEditor2Skin.html\",  \n");
      out.write("          htParams : {\n");
      out.write("              // 툴바 사용 여부 (true:사용/ false:사용하지 않음)\n");
      out.write("              bUseToolbar : true,             \n");
      out.write("              // 입력창 크기 조절바 사용 여부 (true:사용/ false:사용하지 않음)\n");
      out.write("              bUseVerticalResizer : false,     \n");
      out.write("              // 모드 탭(Editor | HTML | TEXT) 사용 여부 (true:사용/ false:사용하지 않음)\n");
      out.write("              bUseModeChanger : true,         \n");
      out.write("              fOnBeforeUnload : function(){\n");
      out.write("                   \n");
      out.write("              }\n");
      out.write("          }, \n");
      out.write("          fOnAppLoad : function(){\n");
      out.write("              //기존 저장된 내용의 text 내용을 에디터상에 뿌려주고자 할때 사용\n");
      out.write("              oEditors.getById[\"ir1\"].exec(\"PASTE_HTML\", [\"\"]);\n");
      out.write("          },\n");
      out.write("          fCreator: \"createSEditor2\"\n");
      out.write("      });\n");
      out.write("      \n");
      out.write("      //저장버튼 클릭시 form 전송\n");
      out.write("      $(\"#save\").click(function(){\n");
      out.write("          oEditors.getById[\"ir1\"].exec(\"UPDATE_CONTENTS_FIELD\", []);\n");
      out.write("          $(\"#frm\").submit();\n");
      out.write("      });    \n");
      out.write("});\n");
      out.write("\n");
      out.write("</script>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<form id=\"frm\" action=\"SemiProjectServlet.do\" method=\"post\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"command\" value=\"qaupdate\"/>\n");
      out.write("\t\t<input type=\"hidden\" name=\"qa_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("\t\t\t<div class=\"Review_header\">\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t\t<h4>Q&A 게시글 수정</h4>\n");
      out.write("\t\t\t\t<p>건의 사항 및 질문 하는 공간</p>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<hr>\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t<div class=\"subject_form\">\n");
      out.write("\t\t\t\t<div class=\"subject\">\n");
      out.write("\t\t\t\t제목\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t\t<input type=\"text\" name=\"title\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.qa_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t</div>       \t\n");
      out.write("        \t<div class=\"content_form\">\n");
      out.write("        \t\t<div class=\"content\">\n");
      out.write("        \t\t\t내용\n");
      out.write("        \t\t\t<textarea rows=\"15\" cols=\"120\" id=\"ir1\" name=\"content\">\n");
      out.write("        \t\t\t ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.qa_content }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\n");
      out.write("        \t\t\t</textarea>\n");
      out.write("        \t\t</div>\n");
      out.write("        \t</div>\n");
      out.write("\t\t\t<div class=\"buttons\">\n");
      out.write("\t\t\t<button type=\"submit\" id=\"save\" class=\"btn btn-primary\">수정하기</button>\n");
      out.write("\t\t\t<button type=\"button\" class=\"btn btn-default\" onclick=\"location.href='SemiProjectServlet.do?command=qadetail&qa_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.qa_id}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("'\">취소</button>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t</form>\n");
      out.write("\t\t\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t\n");
      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".footer{\r\n");
      out.write("\r\n");
      out.write("left: 0;\r\n");
      out.write("bottom: 10px;\r\n");
      out.write("width: 100%;\r\n");
      out.write("background-color: black;\r\n");
      out.write("opacity: 0.8;\r\n");
      out.write("color: silver;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size: small;\r\n");
      out.write("#4c4c4c; \r\n");
      out.write("height: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      <div class=\"footer\">\r\n");
      out.write("         <p>Copyright &copy; ;&nbsp;&nbsp;&nbsp;Website 2018</p>\r\n");
      out.write("         <p>제작자 : 김동민 박우주 성원실 전성은 최강일 최경수</p>\r\n");
      out.write("         <p>제작 일자&nbsp; 2018-12-12</p>\r\n");
      out.write("      </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Bootstrap core JavaScript -->\r\n");
      out.write("   <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
