/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 10:40:19 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.UTC.dto.MemberDto;
import com.UTC.dto.MemberDto;

public final class qa_005fview_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(7);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/usertopbar.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/footer.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KH_semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
    _jspx_dependants.put("/inc/admintopbar.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/topbar.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KH_semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/fmt.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.UTC.dto.MemberDto");
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fchoose;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fotherwise;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fchoose = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fotherwise = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fchoose.release();
    _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.release();
    _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fotherwise.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\n');

	request.setCharacterEncoding("UTF-8");

      out.write('\n');

	response.setContentType("text/html; charset=UTF-8");

      out.write('\n');

	MemberDto dto = (MemberDto) session.getAttribute("dto");

      out.write("\n");
      out.write("<!-- C태그 사용 -->\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 비회원일때 = topbar.jsp / 회원일 때 usertopbar.jsp / 관리자일 떄 admintopbar.jsp-->\n");
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f0_reused = false;
      try {
        _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f0.setParent(null);
        // /qa_view.jsp(16,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto eq null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
        if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\n');
            out.write('	');
            out.write("\r\n");
            out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
            out.write('\r');
            out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
            out.write(" \r\n");
            out.write("<!DOCTYPE html>\r\n");
            out.write("<html>\r\n");
            out.write("\t<head>\r\n");
            out.write("\t<meta charset=\"utf-8\">\r\n");
            out.write("\t<title>UTC</title>\r\n");
            out.write("\t\r\n");
            out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
            out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
            out.write("<script src=\"plugins/handlebars/handlebars-v4.0.5.js\"></script>\r\n");
            out.write("\r\n");
            out.write("<!-- 입력값 유효성 검사 스크립트 -->\r\n");
            out.write("<script type=\"text/javascript\">\r\n");
            out.write("\r\n");
            out.write("//회원가입 폼 비밀번호 유효성 검사\r\n");
            out.write("function pw_check(){\r\n");
            out.write("\t\r\n");
            out.write("\t//패스워드 유효성 체크(문자,숫자,특수문자의 조합으로 6~16자리로)\r\n");
            out.write("\tvar userPw = document.joinform.member_pw;\r\n");
            out.write("\tvar userPwRe = document.joinform.member_pw_re;\r\n");
            out.write("\t\r\n");
            out.write("\t//비밀번호가 같은지 검사\r\n");
            out.write("\tif(userPw.value != userPwRe.value){\r\n");
            out.write("\t\talert(\"비밀번호가 일치하지 않습니다.\");\r\n");
            out.write("\t\treturn false;\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t//비밀번호 6자리 미만이면 알림\r\n");
            out.write("\tif(userPw.value.length < 6){\r\n");
            out.write("\t\talert(\"비밀번호는 6자리 이상으로 만들어주세요.\");\r\n");
            out.write("\t\treturn false;\r\n");
            out.write("\t}\r\n");
            out.write("\t\r\n");
            out.write("\t//비밀번호 생성시 특수문자 섞어서 만들기\r\n");
            out.write("\tif(!userPw.value.match(/([a-zA-Z0-9].*[!,@,#,$,%,^,&,*,?,_,~])|([!,@,#,$,%,^,&,*,?,_,~].*[a-zA-Z0-9])/)){\r\n");
            out.write("\t\talert(\"비밀번호는 특수문자(!@$%^&* 만 허용)를 섞어서 6자리 이상으로 만들어주세요.\");\r\n");
            out.write("\t\treturn false;\r\n");
            out.write("\t}\r\n");
            out.write("\treturn true;\r\n");
            out.write("}\r\n");
            out.write("\r\n");
            out.write("//회원가입 폼 이메일 유효성 검사하기(이메일 형식 검사)\r\n");
            out.write("function email_check(){\r\n");
            out.write("\tvar email = document.getElementById(\"inputEmail\").value;\r\n");
            out.write("\tvar chk_list = /^[A-Za-z0-9_\\.\\-]+@[A-Za-z0-9\\-]+\\.[A-Za-z0-9\\-]+/;\r\n");
            out.write("\t\tif(chk_list.test(email)==false){\r\n");
            out.write("\t\t\talert(\"이메일 형식이 올바르지 않습니다.\");\r\n");
            out.write("\t\t\tdocument.joinform.email.focus();\r\n");
            out.write("\t\t\treturn false;\r\n");
            out.write("\t\t}\r\n");
            out.write("}\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</script>\r\n");
            out.write("</head>\r\n");
            out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
            out.write("<body>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Navigation -->\r\n");
            out.write("<nav class=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<!--  드롭다운-->\r\n");
            out.write("\t<div class=\"container\">\r\n");
            out.write(" \t\t<div class=\"dropdown\">\r\n");
            out.write("    \t\t<button type=\"button\" class=\"btn btn-link\" data-toggle=\"dropdown\">\r\n");
            out.write("      \t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("   \t\t\t</button>\r\n");
            out.write("   \t\t\t\r\n");
            out.write("    \t\t<div class=\"dropdown-menu\">     \t\t\r\n");
            out.write("    \t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=make_up_self\"><strong style=\"color:dark;\">Create My Page</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=list\"><strong style=\"color:dark;\">User Reviews</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=qalist\"><strong style=\"color:dark;\">Q&nbsp;&&nbsp;A Board</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=ntlist\"><strong style=\"color:dark;\">Notice</strong></a>\r\n");
            out.write("\t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=mypage\"><strong style=\"color:dark;\">My page</strong></a>\r\n");
            out.write("    \t\t</div>\r\n");
            out.write("  \t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t<!-- 드롭다운 종료 -->\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<!-- 버튼 -->\n");
            out.write("\t<div class=\"container\">\r\n");
            out.write("\t\t<a class=\"navbar-brand\" href=\"index.jsp\">UTC</a>\r\n");
            out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\" data-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\" aria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
            out.write("            \t<span class=\"navbar-toggler-icon\"></span>\t\t<!-- 화면줄이면 나오는 버튼 -->\r\n");
            out.write("         \t</button>\r\n");
            out.write("         \t\r\n");
            out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
            out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
            out.write("\t\t\t\t\t\t<a id=\"modalButton\" class=\"nav-link\" href=\"loginform.jsp\" data-toggle=\"modal\" data-target=\"#myModal\">Login</a>\n");
            out.write("\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
            out.write("\t\t\t\t\t\t<a class=\"nav-link\" href=\"signup.jsp\" data-toggle=\"modal\" data-target=\"#myModal2\">SignUp</a>\r\n");
            out.write("\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t\t<li>\r\n");
            out.write("\t\t\t\t\t\t\r\n");
            out.write("\t\t\t\t\t</li>\n");
            out.write("\t\t\t\t</ul>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("</nav>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 1 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal3\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 2 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
            out.write(" \t<div class=\"modal-dialog modal-md\">\t\t\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- loginform.jsp가 연결된다. -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t\r\n");
            out.write("\t<!-- Modal 3 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal2\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- signup.jsp 연결(회원정보수정) -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<script type=\"text/javascript\">\r\n");
            out.write("\t\t/** 모달 창이 닫히는 경우의 이벤트 */\r\n");
            out.write("\t\t// \".modal\"로 지정할 경우 : 모든 모달창에 적용됨\r\n");
            out.write("\t\t// \"#아이디\"로 지정할 경우 : 특정 모달 창에 적용\r\n");
            out.write("\t\t$('.modal').on('hidden.bs.modal', function(e) {\r\n");
            out.write("\t\t\t//모달창 내의 내용을 강제로 지움.\r\n");
            out.write("\t\t\t//밑에꺼 안되서 바꿈\r\n");
            out.write("\t\t\t$(this).find('form')[0].reset()\r\n");
            out.write("\t\t\t//$(this).removeData('bs.modal');\r\n");
            out.write("\t\t\t\r\n");
            out.write("\t\t});\r\n");
            out.write("\t</script>\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
        _jspx_th_c_005fif_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
      }
      out.write('\n');
      out.write('\n');
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f1_reused = false;
      try {
        _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f1.setParent(null);
        // /qa_view.jsp(20,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getMember_role() eq 'ADMIN' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
        if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\n');
            out.write('	');

	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-control", "no-store");
	response.setHeader("Expires", "0");
	//세션 삭제 코드

            out.write("\r\n");
            out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
            out.write('\r');
            out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<!DOCTYPE html>\r\n");
            out.write("<html>\r\n");
            out.write("<head>\r\n");
            out.write("<meta charset=\"utf-8\">\r\n");
            out.write("<title>UTC</title>\r\n");
            out.write("\r\n");
            out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link\r\n");
            out.write("\thref=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\"\r\n");
            out.write("\trel=\"stylesheet\">\r\n");
            out.write("<link\r\n");
            out.write("\thref=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\"\r\n");
            out.write("\trel=\"stylesheet\">\r\n");
            out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\">\r\n");
            out.write("<link\r\n");
            out.write("\thref=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\"\r\n");
            out.write("\trel=\"stylesheet\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<!-- <script src=\"plugins/ajax/ajax_helper.js\"></script> -->\r\n");
            out.write("<!-- <script src=\"http://code.jquery.com/jquery.min.js\"></script> -->\r\n");
            out.write("<script\r\n");
            out.write("\tsrc=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
            out.write("<script\r\n");
            out.write("\tsrc=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</head>\r\n");
            out.write("\r\n");
            out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
            out.write("<body>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Navigation -->\r\n");
            out.write("\t<nav\r\n");
            out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t<!--  드롭다운-->\r\n");
            out.write("\t\t<div class=\"container\">\r\n");
            out.write("\t\t\t<div class=\"dropdown\">\r\n");
            out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-link\" data-toggle=\"dropdown\">\r\n");
            out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("\t\t\t\t</button>\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t<div class=\"dropdown-menu\">\r\n");
            out.write("\t\t\t\t\t<a class=\"dropdown-item\" href=\"make_up_self.jsp\"><strong style=\"color:dark;\">Create My Page</strong></a> <a\r\n");
            out.write("\t\t\t\t\t\tclass=\"dropdown-item\" href=\"SemiProjectServlet.do?command=admin_rvlist\"><strong style=\"color:dark;\">User Reviews</strong></a> <a\r\n");
            out.write("\t\t\t\t\t\tclass=\"dropdown-item\" href=\"SemiProjectServlet.do?command=admin_qalist\"><strong style=\"color:dark;\">Q&nbsp;&&nbsp;A Board</strong></a>\r\n");
            out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"SemiProjectServlet.do?command=admin_ntlist\"><strong style=\"color:dark;\">Notice</strong></a>\r\n");
            out.write("\t\t\t\t\t\t<a class=\"dropdown-item\" href=\"SemiProjectServlet.do?command=selectAll\"><strong style=\"color:dark;\">Member Views</strong></a>\r\n");
            out.write("\t\t\t\t</div>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t\t<!-- 드롭다운 종료 -->\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t<!-- 버튼 -->\r\n");
            out.write("\t\t<div class=\"container\">\r\n");
            out.write("\t\t\t<a class=\"navbar-brand\" href=\"admin_main.jsp\">UTC</a>\r\n");
            out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
            out.write("\t\t\t\tdata-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
            out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
            out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("\t\t\t\t<!-- 화면줄이면 나오는 버튼 -->\r\n");
            out.write("\t\t\t</button>\r\n");
            out.write("\r\n");
            out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
            out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\">\r\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" style=\"color: white;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("</a></li>\r\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\"><a class=\"nav-link\" href=\"SemiProjectServlet.do?command=logout\">Logout</a>\r\n");
            out.write("\t\t\t\t\t</li>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t\t\t</ul>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</nav>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 1 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal3\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 2 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- loginform.jsp가 연결된다. -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 3 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal2\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- signup.jsp 연결(회원정보수정) -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<script type=\"text/javascript\">\r\n");
            out.write("\t\t/** 모달 창이 닫히는 경우의 이벤트 */\r\n");
            out.write("\t\t// \".modal\"로 지정할 경우 : 모든 모달창에 적용됨\r\n");
            out.write("\t\t// \"#아이디\"로 지정할 경우 : 특정 모달 창에 적용\r\n");
            out.write("\t\t$('.modal').on('hidden.bs.modal', function(e) {\r\n");
            out.write("\t\t\t// 모달창 내의 내용을 강제로 지움.\r\n");
            out.write("\t\t\t$(this).removeData('bs.modal');\r\n");
            out.write("\t\t});\r\n");
            out.write("\t</script>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
            out.write('\n');
            out.write('	');
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
        _jspx_th_c_005fif_005f1_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
      }
      out.write('\n');
      out.write('\n');
      //  c:if
      org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
      boolean _jspx_th_c_005fif_005f2_reused = false;
      try {
        _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
        _jspx_th_c_005fif_005f2.setParent(null);
        // /qa_view.jsp(25,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
        _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.getMember_role() eq 'USER' }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
        int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
        if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write('\n');
            out.write('	');

	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-control", "no-store");
	response.setHeader("Expires", "0");
	//세션 삭제 코드

            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
            out.write('\r');
            out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\r\n");
            out.write("<!DOCTYPE html>\r\n");
            out.write("<html>\r\n");
            out.write("\r\n");
            out.write("<head>\r\n");
            out.write("<meta charset=\"utf-8\">\r\n");
            out.write("<title>UTC</title>\r\n");
            out.write("\r\n");
            out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\">\r\n");
            out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
            out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
            out.write("<script src=\"plugins/handlebars/handlebars-v4.0.5.js\"></script>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</head>\r\n");
            out.write("\r\n");
            out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
            out.write("<body>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Navigation -->\r\n");
            out.write("\t<nav\r\n");
            out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t<!--  드롭다운-->\r\n");
            out.write("\t\t<div class=\"container\">\r\n");
            out.write("\t\t\t<div class=\"dropdown\">\r\n");
            out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-link\" data-toggle=\"dropdown\">\r\n");
            out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("\t\t\t\t</button>\r\n");
            out.write("\n");
            out.write("    \t\t<div class=\"dropdown-menu\">     \t\t\r\n");
            out.write("    \t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=make_up_self\"><strong style=\"color:dark;\">Create My Page</strong></a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=list\" class=\"is-current\">User Reviews</a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=qalist\">Q&nbsp;&&nbsp;A Board</a>\r\n");
            out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=ntlist\">Notice</a>\r\n");
            out.write("\t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=mypage\"><strong style=\"color:dark;\">My page</strong></a>\r\n");
            out.write("    \t\t</div>\r\n");
            out.write("\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t\t<!-- 드롭다운 종료 -->\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t\t<!-- 버튼 -->\r\n");
            out.write("\t\t<div class=\"container\">\r\n");
            out.write("\t\t\t<a class=\"navbar-brand\" href=\"user_main.jsp\">UTC</a>\r\n");
            out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
            out.write("\t\t\t\tdata-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
            out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
            out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
            out.write("\t\t\t\t<!-- 화면줄이면 나오는 버튼 -->\r\n");
            out.write("\t\t\t</button>\r\n");
            out.write("\r\n");
            out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
            out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
            out.write("\t\t\t\t\t<li class=\"nav-item\"><li class=\"nav-item\"><a class=\"nav-link\" style=\"color: white;\">");
            out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
            out.write("님 환영합니다!</a></li>\r\n");
            out.write("               <li class=\"nav-item\"><a class=\"nav-link\"\r\n");
            out.write("\t\t\t\t\t\thref=\"SemiProjectServlet.do?command=logout\">Logout</a>\r\n");
            out.write("\t\t\t\t\t</li>\r\n");
            out.write("\t\t\t\t</ul>\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("</nav>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 1 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal3\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\t<!-- Modal 2 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- loginform.jsp가 연결된다. -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\t\r\n");
            out.write("\t<!-- Modal 3 -->\r\n");
            out.write("\t<div class=\"modal fade\" id=\"myModal2\">\r\n");
            out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
            out.write("\t\t\t<div class=\"modal-content\">\r\n");
            out.write("\t\t\t\t<!-- signup.jsp 연결(회원정보수정) -->\r\n");
            out.write("\t\t\t</div>\r\n");
            out.write("\t\t</div>\r\n");
            out.write("\t</div>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\t<script type=\"text/javascript\">\r\n");
            out.write("\t\t/** 모달 창이 닫히는 경우의 이벤트 */\r\n");
            out.write("\t\t// \".modal\"로 지정할 경우 : 모든 모달창에 적용됨\r\n");
            out.write("\t\t// \"#아이디\"로 지정할 경우 : 특정 모달 창에 적용\r\n");
            out.write("\t\t$('.modal').on('hidden.bs.modal', function(e) {\r\n");
            out.write("\t\t\t// 모달창 내의 내용을 강제로 지움.\r\n");
            out.write("\t\t\t$(this).removeData('bs.modal');\r\n");
            out.write("\t\t});\r\n");
            out.write("\t</script>\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("\r\n");
            out.write("</body>\r\n");
            out.write("</html>");
            out.write('\n');
            int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
        _jspx_th_c_005fif_005f2_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f2_reused);
      }
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>UTC</title>\n");
      out.write("<!-- ReviewWrite css 참조 -->\n");
      out.write("<link href=\"css/ReviewView.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\n");
      out.write("<link href=\"css/index_menu.css\" rel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link\n");
      out.write("\thref=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\"\n");
      out.write("\trel=\"stylesheet\">\n");
      out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\n");
      out.write("\n");
      out.write("<!-- fontawsome 사용 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"https://use.fontawesome.com/releases/v5.5.0/css/all.css\" integrity=\"sha384-B4dIYHKNBt8Bc12p+WXckhzcICo0wtJAoU8YZTY5qE0Id1GSseTk6S+L3BlXeVIU\" crossorigin=\"anonymous\">\n");
      out.write("\n");
      out.write("<script src=\"plugins/ajax-form/jquery.form.min.js\"></script>\n");
      out.write("\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- qaViewDto를 사용할 수 있게 세팅해줌 -->\n");
      out.write("\t");
      com.UTC.dto.QABoardDto qaViewDto = null;
      qaViewDto = (com.UTC.dto.QABoardDto) _jspx_page_context.getAttribute("qaViewDto", javax.servlet.jsp.PageContext.REQUEST_SCOPE);
      if (qaViewDto == null){
        qaViewDto = new com.UTC.dto.QABoardDto();
        _jspx_page_context.setAttribute("qaViewDto", qaViewDto, javax.servlet.jsp.PageContext.REQUEST_SCOPE);
        out.write('\n');
        out.write('	');
      }
      out.write("\n");
      out.write("\n");
      out.write("\t<div class=\"container\">\n");
      out.write("\t\t<div class=\"Review_header\">\n");
      out.write("\t\t\t<h4>Q&A게시판</h4>\n");
      out.write("\t\t\t<p>홈페이지에 대해 궁금한 점을 남겨주세요.</p>\n");
      out.write("\t\t\t");

				if (dto != null && dto.getMember_email().equals(qaViewDto.getMember_email())) {
			
      out.write("\n");
      out.write("\t\t\t<div class=\"button_container\">\n");
      out.write("\t\t\t\t<div class=\"update_button\">\n");
      out.write("\t\t\t\t\t<a class=\"upde\"\n");
      out.write("\t\t\t\t\t\thref=\"SemiProjectServlet.do?command=qaupdateform&qa_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaViewDto.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" class=\"btn btn-primary\" style=\"text-align: right;\">수정</button></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div class=\"delete_button\">\n");
      out.write("\t\t\t\t\t<a class=\"upde\"\n");
      out.write("\t\t\t\t\t\thref=\"SemiProjectServlet.do?command=qadelete&qa_id=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaViewDto.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"><button\n");
      out.write("\t\t\t\t\t\t\ttype=\"submit\" class=\"btn btn-danger\" style=\"text-align: right;\">삭제</button></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t");

				} else {

				}
			
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t<div class=\"subject_form\">\n");
      out.write("\t\t\t<div class=\"subject\">제목</div>\n");
      out.write("\t\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t\t");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.UTC.dto.QABoardDto)_jspx_page_context.findAttribute("qaViewDto")).getQa_title())));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<div class=\"writer_form\">\n");
      out.write("\t\t\t<div class=\"write\">글쓴이</div>\n");
      out.write("\t\t\t<div class=\"writer\">\n");
      out.write("\t\t\t\t");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.UTC.dto.QABoardDto)_jspx_page_context.findAttribute("qaViewDto")).getMember_name())));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"hit\">\n");
      out.write("\t\t\t\t조회수 : &nbsp;&nbsp;");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.UTC.dto.QABoardDto)_jspx_page_context.findAttribute("qaViewDto")).getQa_view_cnt())));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t\t<div class=\"date_form\">\n");
      out.write("\t\t\t\t작성일 :&nbsp;&nbsp;\n");
      out.write("\t\t\t\t");
      if (_jspx_meth_fmt_005fformatDate_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<br>\n");
      out.write("\t\t<!-- 글 내용이 들어가는 부분 -->\n");
      out.write("\t\t<div class=\"content_form\">\n");
      out.write("\t\t\t<div class=\"content\">\n");
      out.write("\t\t\t\t<!-- 게시글 내용 -->\n");
      out.write("\t\t\t\t");
      out.write(org.apache.jasper.runtime.JspRuntimeLibrary.toString((((com.UTC.dto.QABoardDto)_jspx_page_context.findAttribute("qaViewDto")).getQa_content())));
      out.write("\n");
      out.write("\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\n");
      out.write("<div class=\"comment_container\">\n");
      out.write("\t<form id=\"comment_form\" method=\"post\" action=\"CommentInsert.do\" onsubmit=\"return comment_ajax(this);\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"command\" value=\"insertQAComment\"/>\n");
      out.write("\t\t<input type=\"hidden\" name=\"qa_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaViewDto.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t\t<div class=\"comment_form\" >\n");
      out.write("\n");
      out.write(" \t\t<div id=\"comment_list\" > \t\t\t\n");
      out.write("\n");
      out.write(" \t\t</div>\n");
      out.write(" \t\t<hr>\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"comment_content\">\n");
      out.write("\t\t\t<textarea rows=\"3\" cols=\"120\" name=\"qacomment_content\"></textarea>\n");
      out.write("\t\t\t<div class=\"insert_button\">\n");
      out.write("\t\t\t\t<button type=\"submit\" class=\"btn btn-default\">등록</button>\n");
      out.write("\t\t\t</div>\n");
      out.write("\t\t</div>\n");
      out.write("\t</form>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\t<div style=\"text-align: right;\">\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"location.href='SemiProjectServlet.do?command=qalist'\">목록으로</button>\n");
      out.write("\t</div>\n");
      out.write("\t<br>\n");
      out.write("\t<br>\n");
      out.write("\t\n");
      out.write("\t\t\t<div class=\"prev_next\">\n");
      out.write("\t\t<div class=\"prev\">\n");
      out.write("\t\t\t<b>이전글</b>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f0(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t\t<div class=\"next\">\n");
      out.write("\t\t\t<b>다음글</b>\n");
      out.write("\t\t\t");
      if (_jspx_meth_c_005fchoose_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".footer{\r\n");
      out.write("\r\n");
      out.write("left: 0;\r\n");
      out.write("bottom: 10px;\r\n");
      out.write("width: 100%;\r\n");
      out.write("background-color: black;\r\n");
      out.write("opacity: 0.8;\r\n");
      out.write("color: silver;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size: small;\r\n");
      out.write("#4c4c4c; \r\n");
      out.write("height: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      <div class=\"footer\">\r\n");
      out.write("         <p>Copyright &copy; ;&nbsp;&nbsp;&nbsp;Website 2018</p>\r\n");
      out.write("         <p>제작자 : 김동민 박우주 성원실 전성은 최강일 최경수</p>\r\n");
      out.write("         <p>제작 일자&nbsp; 2018-12-12</p>\r\n");
      out.write("      </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Bootstrap core JavaScript -->\r\n");
      out.write("   <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 덧글 항목에 대한 템플릿 참조 -->\n");
      out.write("<script id=\"tmpl_comment_item\" type=\"text/x-handlebars-template\">\n");
      out.write("\n");
      out.write("\t<li class=\"media\" style='border-top: 1px dotted #ccc; padding-top: 15px;' id=\"{{qacomment_id}}\">\n");
      out.write("\t\t<div class=\"media-body\" style='display: block;'>\n");
      out.write("\t\t\t<h4 class=\"media-heading clearfix\">\n");
      out.write("\t\t\t\t<!--작성자, 작성일시 -->\n");
      out.write("\t\t\t\t<div class='pull-left'>\n");
      out.write("\t\t\t\t\t{{member_name}}\n");
      out.write("\t\t\t\t\t<small style='margin-left: 30px;'>\n");
      out.write("\t\t\t\t\t\t{{qaregdate}}\n");
      out.write("\t\t\t\t\t</small>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!-- 삭제 버튼 -->\n");
      out.write("\t\t\t\t<div class='pull-right'>\n");
      out.write("\t\t\t\t\t<a onclick=\"comment_delete('{{qacomment_id}}');\" data-toggle=\"modal\"\n");
      out.write("\t\t\t\t\tclass='btn btn-danger btn-xs'>\n");
      out.write("\t\t\t\t\t\t<i class=\"far fa-trash-alt\"></i>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t\t<!--수정 버튼 -->\n");
      out.write("\t\t\t\t<div class='pull-right'>\n");
      out.write("\t\t\t\t\t<a onclick=\"comment_edit('{{qacomment_id}}');\" data-toggle=\"modal\" \n");
      out.write("\t\t\t\t\tclass='btn btn-warning btn-xs'>\n");
      out.write("\t\t\t\t\t\t<i class=\"far fa-edit\"></i>\n");
      out.write("\t\t\t\t\t</a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\n");
      out.write("\t\t\t</h4>\n");
      out.write("\t\t\t<!--내용 -->\n");
      out.write("\t\t\t<p>{{{qacomment_content}}}</p>\n");
      out.write("\t\t</div>\n");
      out.write("\t</li>\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("\n");
      out.write("<!-- 댓글 수정 시 사용될 Modal -->\n");
      out.write("<div class=\"modal fade\" id=\"comment_edit_modal\">\n");
      out.write("\t<div class=\"modal-dialog\">\n");
      out.write("\t\t<div class=\"modal-content\">\n");
      out.write("\t\t\t<form id=\"comment_edit_modal\" method=\"post\" name=\"qacomment_id\" action=\"CommentEditOk.do\">\n");
      out.write("\n");
      out.write("\t<input type=\"hidden\" name=\"command\" value=\"updateQAComment\"/>\n");
      out.write("\t<input type=\"hidden\" name=\"qacomment_id\" value=\"\" />\n");
      out.write("\t<input type=\"hidden\" name=\"member_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("\t<div class=\"modal-header\">\n");
      out.write("\t\t\n");
      out.write("\t\t<h5 class=\"modal-title\">덧글 수정</h5>\n");
      out.write("\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" \n");
      out.write("\t\t\taria-label=\"Close\"><span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t</button>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"modal-body\">\n");
      out.write("\t\t\n");
      out.write("\t\t<div class=\"form-group\">\n");
      out.write("\t\t\t<textarea class=\"form-control\" name=\"qacomment_content\" rows=\"2\" cols=\"55\"></textarea>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"modal-footer\">\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-basic\" data-dismiss=\"modal\">취소</button>\n");
      out.write("\t\t<button type=\"submit\" class=\"btn btn-danger\">수정</button>\n");
      out.write("\t</div>\n");
      out.write("</form>\n");
      out.write("\t\t</div>\n");
      out.write("\t</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("<!-- 삭제 시 사용될 모달 -->\n");
      out.write("<div class=\"modal fade\" id=\"comment_delete_modal\">\n");
      out.write("<div class=\"modal-dialog\">\n");
      out.write("<div class=\"modal-content\">\n");
      out.write("<form id=\"comment_delete_form\" method=\"post\" action=\"CommentDeleteOk.do\">\n");
      out.write("\t<input type=\"hidden\" name=\"qacomment_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qacommentId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" />\n");
      out.write("\t<input type=\"hidden\" name=\"member_id\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"/>\n");
      out.write("\t<div class=\"modal-header\">\n");
      out.write("\t\t<h5 class=\"modal-title-2\">덧글 삭제</h5>\n");
      out.write("\t\t<button type=\"button\" class=\"close\" data-dismiss=\"modal\" \n");
      out.write("\t\t\taria-label=\"Close\"><span aria-hidden=\"true\">&times;</span>\n");
      out.write("\t\t</button>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"modal-body\">\n");
      out.write("\t\t<p>정말 이 덧글을 삭제하시겠습니까?</p>\n");
      out.write("\t</div>\n");
      out.write("\t<div class=\"modal-footer\">\n");
      out.write("\t\t<button type=\"button\" class=\"btn btn-basic\" data-dismiss=\"modal\">취소</button>\n");
      out.write("\t\t<button type=\"submit\" class=\"btn btn-danger\" >삭제</button>\n");
      out.write("\t</div>\n");
      out.write("</form>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("\n");
      out.write("\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\tcomment_list('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaViewDto.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\tfunction comment_ajax(f){\n");
      out.write("\t\t\n");
      out.write("\t\tvar param = $(f).serialize();\t\t//폼의 데이터를 urlencdoing 방식으로 변환해준다.\n");
      out.write("\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t    url: \"CommentInsert.do\", \t// 클라이언트가 요청을 보낼 서버의 URL 주소\n");
      out.write("\t\t    data: param,                // HTTP 요청과 함께 서버로 보낼 데이터\n");
      out.write("\t\t    type: \"POST\",                             // HTTP 요청 방식(GET, POST)\n");
      out.write("\t\t    dataType: \"json\",                         // 서버에서 보내줄 데이터의 타입\n");
      out.write("\t\t    success: function(data){\n");
      out.write("\t\t    \t$(\"textarea[name=qacomment_content]\").val(\"\");\n");
      out.write("\t\t    \tcomment_list(data.item.qa_id);\n");
      out.write("\t\t    }\n");
      out.write("\t\t});\n");
      out.write("\t\treturn false;\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\tfunction comment_list(qa_id) {\n");
      out.write("\t\t// qa_id 가 없을 경우 에러로 봐서 List를 가져오지 않는다.\n");
      out.write("\t\tif(qa_id == 0){\n");
      out.write("\t\t\talert(\"qa_id가 존재하지 않습니다.\");\n");
      out.write("\t\t\treturn false;\n");
      out.write("\t\t}\n");
      out.write("\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t    url: \"CommentList.do?command=selectAllQAComment&qa_id=\"+qa_id, \t\t\t\t\t// 클라이언트가 요청을 보낼 서버의 URL 주소\n");
      out.write("\t\t    type: \"GET\",                             // HTTP 요청 방식(GET, POST)\n");
      out.write("\t\t    dataType: \"json\",                         // 서버에서 보내줄 데이터의 타입\n");
      out.write("\t\t    success: function(json){\n");
      out.write("// \t\t    \tif (json.rt != \"OK\") {\n");
      out.write("// \t\t\t\t\talert(json.rt);\n");
      out.write("// \t\t\t\t\treturn false;\n");
      out.write("// \t\t\t\t}\n");
      out.write("\n");
      out.write("  \t\t    \tvar data = json.item;\n");
      out.write("  \t\t    \tvar template = Handlebars.compile($(\"#tmpl_comment_item\").html());\n");
      out.write("  \t\t    \t$(\"#comment_list\").empty();\n");
      out.write("  \t\t    \t\n");
      out.write(" \t\t    \tfor(var i =0; i<data.length; i++){\n");
      out.write(" \t\t    \t\tvar html = template(data[i]);\n");
      out.write(" \t\t    \t\t$(\"#comment_list\").append(html);\n");
      out.write(" \t\t    \t}\n");
      out.write("\t\t    }\n");
      out.write("\t\t})\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t$(document).on('submit', \"#comment_edit_modal\", function (e) {\n");
      out.write("\t\tconsole.log(\"test21\");\n");
      out.write("\t\t\n");
      out.write("\t\tvar param = $(this).serialize();\n");
      out.write("\t\t\t\n");
      out.write("\t\t$.ajax({\n");
      out.write("\t\t    url: \"CommentEditOk.do\", \t// 클라이언트가 요청을 보낼 서버의 URL 주소\n");
      out.write("\t\t    data: param,                // HTTP 요청과 함께 서버로 보낼 데이터\n");
      out.write("\t\t    type: \"POST\",                             // HTTP 요청 방식(GET, POST)\n");
      out.write("\t\t    dataType: \"json\",                         // 서버에서 보내줄 데이터의 타입\n");
      out.write("\t\t    success: function(json){\n");
      out.write("\t \t\t\tvar template = Handlebars.compile($(\"#tmpl_comment_item\").html());\n");
      out.write("\t\t\t\t\n");
      out.write("\t \t\t\tconsole.log(json);\n");
      out.write("\t \t\t\tvar html = template(json.item);\n");
      out.write("\t \t\t\t$(\"#\" + json.item.id).replaceWith(html);\n");
      out.write("\t\t\t\t\t\t\t\n");
      out.write("\t \t\t\t$(\"#comment_edit_modal\").modal('hide');\n");
      out.write("\t \t\t\t$('#comment_edit_modal').on('hide.bs.modal');\n");
      out.write("\t \t\t\tconsole.log(\"test4\");\n");
      out.write("\t \t\t\tcomment_list(json.item.qa_id);\n");
      out.write("\t\t    }\n");
      out.write("\t\t});\n");
      out.write("\t\treturn false;\t\n");
      out.write("\t});\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t//모달창 띄우기\n");
      out.write("\tfunction comment_edit(id) {\n");
      out.write("\t\t$(\"#comment_edit_modal\").modal();\n");
      out.write("\t\t//console.log(id);\n");
      out.write("\t\tvar text = $(\"#\"+id).find(\".media-body p\").text();\n");
      out.write("\t\t//console.log(text);\n");
      out.write("\t\t$(\"#comment_edit_modal input[name=qacomment_id]\").val(id);\n");
      out.write("\t\t$(\"#comment_edit_modal textarea\").val(text);\n");
      out.write("\t\n");
      out.write("\t\tconsole.log(\"test1\");\n");
      out.write("\t\t\n");
      out.write("\t};\n");
      out.write("\n");
      out.write("\t\n");
      out.write("\tfunction comment_delete(id) {\n");
      out.write("\t\t$(\"#comment_delete_modal\").modal();\n");
      out.write("\t\t$(\"#comment_delete_modal input[name=qacomment_id]\").val(id);\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\t$(document).on('submit',\"#comment_delete_form\", function(e){\n");
      out.write("\t\tvar items = $(this).serialize();\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"CommentDeleteOk.do\",\n");
      out.write("            type: \"POST\",\n");
      out.write("            data: items,\n");
      out.write("            dataType: \"json\",\n");
      out.write("\t\t\tsuccess: function(data) {\n");
      out.write("\t\t\t\tcomment_list('");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaViewDto.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("');\n");
      out.write("\t\t\t\t$(\".modal\").modal('hide');\n");
      out.write("\t\t\t}\n");
      out.write("        });\n");
      out.write("        return false;\n");
      out.write("    });\n");
      out.write("\t\n");
      out.write("\t\t\t\n");
      out.write("</script>\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("\t\n");
      out.write("\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_fmt_005fformatDate_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  fmt:formatDate
    org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag _jspx_th_fmt_005fformatDate_005f0 = (org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag) _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.get(org.apache.taglibs.standard.tag.rt.fmt.FormatDateTag.class);
    boolean _jspx_th_fmt_005fformatDate_005f0_reused = false;
    try {
      _jspx_th_fmt_005fformatDate_005f0.setPageContext(_jspx_page_context);
      _jspx_th_fmt_005fformatDate_005f0.setParent(null);
      // /qa_view.jsp(101,4) name = value type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setValue((java.util.Date) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${qaViewDto.qa_regdate }", java.util.Date.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /qa_view.jsp(101,4) name = pattern type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_fmt_005fformatDate_005f0.setPattern("yyyy.MM.dd");
      int _jspx_eval_fmt_005fformatDate_005f0 = _jspx_th_fmt_005fformatDate_005f0.doStartTag();
      if (_jspx_th_fmt_005fformatDate_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ffmt_005fformatDate_0026_005fvalue_005fpattern_005fnobody.reuse(_jspx_th_fmt_005fformatDate_005f0);
      _jspx_th_fmt_005fformatDate_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_fmt_005fformatDate_005f0, _jsp_getInstanceManager(), _jspx_th_fmt_005fformatDate_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f0 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f0_reused = false;
    try {
      _jspx_th_c_005fchoose_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f0.setParent(null);
      int _jspx_eval_c_005fchoose_005f0 = _jspx_th_c_005fchoose_005f0.doStartTag();
      if (_jspx_eval_c_005fchoose_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f0(_jspx_th_c_005fchoose_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f0);
      _jspx_th_c_005fchoose_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f0 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f0_reused = false;
    try {
      _jspx_th_c_005fwhen_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      // /qa_view.jsp(148,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prevDocument != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f0 = _jspx_th_c_005fwhen_005f0.doStartTag();
      if (_jspx_eval_c_005fwhen_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005furl_005f0(_jspx_th_c_005fwhen_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prevUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prevDocument.qa_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f0);
      _jspx_th_c_005fwhen_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f0);
      // /qa_view.jsp(149,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setVar("prevUrl");
      // /qa_view.jsp(149,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("SemiProjectServlet.do?command=qadetail");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005furl_005f0);
        }
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fparam_005f0(_jspx_th_c_005furl_005f0, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005furl_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005furl_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f0 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f0_reused = false;
    try {
      _jspx_th_c_005fparam_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f0);
      // /qa_view.jsp(150,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setName("qa_id");
      // /qa_view.jsp(150,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f0.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${prevDocument.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f0 = _jspx_th_c_005fparam_005f0.doStartTag();
      if (_jspx_th_c_005fparam_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f0);
      _jspx_th_c_005fparam_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f0 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f0_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f0);
      int _jspx_eval_c_005fotherwise_005f0 = _jspx_th_c_005fotherwise_005f0.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t이전글이 없습니다.\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f0);
      _jspx_th_c_005fotherwise_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fchoose_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:choose
    org.apache.taglibs.standard.tag.common.core.ChooseTag _jspx_th_c_005fchoose_005f1 = (org.apache.taglibs.standard.tag.common.core.ChooseTag) _005fjspx_005ftagPool_005fc_005fchoose.get(org.apache.taglibs.standard.tag.common.core.ChooseTag.class);
    boolean _jspx_th_c_005fchoose_005f1_reused = false;
    try {
      _jspx_th_c_005fchoose_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fchoose_005f1.setParent(null);
      int _jspx_eval_c_005fchoose_005f1 = _jspx_th_c_005fchoose_005f1.doStartTag();
      if (_jspx_eval_c_005fchoose_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fwhen_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t");
          if (_jspx_meth_c_005fotherwise_005f1(_jspx_th_c_005fchoose_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fchoose_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fchoose_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fchoose.reuse(_jspx_th_c_005fchoose_005f1);
      _jspx_th_c_005fchoose_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fchoose_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fchoose_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fwhen_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:when
    org.apache.taglibs.standard.tag.rt.core.WhenTag _jspx_th_c_005fwhen_005f1 = (org.apache.taglibs.standard.tag.rt.core.WhenTag) _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.WhenTag.class);
    boolean _jspx_th_c_005fwhen_005f1_reused = false;
    try {
      _jspx_th_c_005fwhen_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fwhen_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      // /qa_view.jsp(162,4) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fwhen_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nextDocument != null }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fwhen_005f1 = _jspx_th_c_005fwhen_005f1.doStartTag();
      if (_jspx_eval_c_005fwhen_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t");
          if (_jspx_meth_c_005furl_005f1(_jspx_th_c_005fwhen_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t<a href=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nextUrl }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('"');
          out.write('>');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nextDocument.qa_title }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("</a>\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fwhen_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fwhen_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fwhen_0026_005ftest.reuse(_jspx_th_c_005fwhen_005f1);
      _jspx_th_c_005fwhen_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fwhen_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fwhen_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005furl_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fwhen_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f1 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f1_reused = false;
    try {
      _jspx_th_c_005furl_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fwhen_005f1);
      // /qa_view.jsp(163,5) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setVar("nextUrl");
      // /qa_view.jsp(163,5) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f1.setValue("SemiProjectServlet.do?command=qadetail");
      int _jspx_eval_c_005furl_005f1 = _jspx_th_c_005furl_005f1.doStartTag();
      if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_c_005furl_005f1);
        }
        do {
          out.write("\n");
          out.write("\t\t\t\t\t\t");
          if (_jspx_meth_c_005fparam_005f1(_jspx_th_c_005furl_005f1, _jspx_page_context))
            return true;
          out.write("\n");
          out.write("\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005furl_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_c_005furl_005f1 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_c_005furl_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvar_005fvalue.reuse(_jspx_th_c_005furl_005f1);
      _jspx_th_c_005furl_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f1, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fparam_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005furl_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:param
    org.apache.taglibs.standard.tag.rt.core.ParamTag _jspx_th_c_005fparam_005f1 = (org.apache.taglibs.standard.tag.rt.core.ParamTag) _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ParamTag.class);
    boolean _jspx_th_c_005fparam_005f1_reused = false;
    try {
      _jspx_th_c_005fparam_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fparam_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005furl_005f1);
      // /qa_view.jsp(164,6) name = name type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setName("qa_id");
      // /qa_view.jsp(164,6) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fparam_005f1.setValue((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${nextDocument.qa_id }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      int _jspx_eval_c_005fparam_005f1 = _jspx_th_c_005fparam_005f1.doStartTag();
      if (_jspx_th_c_005fparam_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fparam_0026_005fvalue_005fname_005fnobody.reuse(_jspx_th_c_005fparam_005f1);
      _jspx_th_c_005fparam_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fparam_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fparam_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fotherwise_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fchoose_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:otherwise
    org.apache.taglibs.standard.tag.common.core.OtherwiseTag _jspx_th_c_005fotherwise_005f1 = (org.apache.taglibs.standard.tag.common.core.OtherwiseTag) _005fjspx_005ftagPool_005fc_005fotherwise.get(org.apache.taglibs.standard.tag.common.core.OtherwiseTag.class);
    boolean _jspx_th_c_005fotherwise_005f1_reused = false;
    try {
      _jspx_th_c_005fotherwise_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fotherwise_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fchoose_005f1);
      int _jspx_eval_c_005fotherwise_005f1 = _jspx_th_c_005fotherwise_005f1.doStartTag();
      if (_jspx_eval_c_005fotherwise_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("\t\t\t\t\t다음글이 없습니다.\n");
          out.write("\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fotherwise_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fotherwise_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fotherwise.reuse(_jspx_th_c_005fotherwise_005f1);
      _jspx_th_c_005fotherwise_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fotherwise_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fotherwise_005f1_reused);
    }
    return false;
  }
}
