/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.43
 * Generated at: 2020-04-09 10:34:03 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import com.UTC.dao.RVdocumentDao;
import com.UTC.dto.RVdocumentDto;
import java.util.List;
import com.UTC.dto.MemberDto;

public final class user_005fmain_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/usertopbar.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("/inc/footer.jsp", Long.valueOf(1566187849000L));
    _jspx_dependants.put("jar:file:/Users/kdm/JavaWorkspace/kh_semi/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/KH_semi/WEB-INF/lib/taglibs-standard-impl-1.2.5.jar!/META-INF/c.tld", Long.valueOf(1425946270000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("com.UTC.dto.RVdocumentDto");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("com.UTC.dto.MemberDto");
    _jspx_imports_classes.add("com.UTC.dao.RVdocumentDao");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\t<head>\r\n");
      out.write("\t<meta charset=\"utf-8\">\r\n");
      out.write("<title>UTC</title>\t\t\r\n");
      out.write("\t\t\r\n");
      out.write("\t<!-- 강일 슬라이더 넣은 부분 -->\t\r\n");
      out.write("\t<style type=\"text/css\">\r\n");
      out.write("  \t  \ttextarea, iframe{\r\n");
      out.write("        display: block;\r\n");
      out.write("        margin: 10px 0;\r\n");
      out.write("    \t}\r\n");
      out.write("\t</style>\r\n");
      out.write("\r\n");
      out.write("<!-- <script src=\"https://code.jquery.com/jquery-1.12.4.min.js\"></script> -->\r\n");
      out.write("\r\n");

RVdocumentDao dao= new RVdocumentDao();
List<RVdocumentDto> list = dao.selectTen();

      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t");

	response.setHeader("Pragma", "no-cache");
	response.setHeader("Cache-control", "no-store");
	response.setHeader("Expires", "0");
	//세션 삭제 코드

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"utf-8\">\r\n");
      out.write("<title>UTC</title>\r\n");
      out.write("\r\n");
      out.write("<link href=\"vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"css/one-page-wonder.min.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\">\r\n");
      out.write("<link href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("<script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<script src=\"plugins/handlebars/handlebars-v4.0.5.js\"></script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Navigation -->\r\n");
      out.write("\t<nav\r\n");
      out.write("\t\tclass=\"navbar navbar-expand-lg navbar-dark navbar-custom fixed-top\">\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!--  드롭다운-->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"dropdown\">\r\n");
      out.write("\t\t\t\t<button type=\"button\" class=\"btn btn-link\" data-toggle=\"dropdown\">\r\n");
      out.write("\t\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t</button>\r\n");
      out.write("\n");
      out.write("    \t\t<div class=\"dropdown-menu\">     \t\t\r\n");
      out.write("    \t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=make_up_self\"><strong style=\"color:dark;\">Create My Page</strong></a>\r\n");
      out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=list\" class=\"is-current\">User Reviews</a>\r\n");
      out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=qalist\">Q&nbsp;&&nbsp;A Board</a>\r\n");
      out.write("  \t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=ntlist\">Notice</a>\r\n");
      out.write("\t\t\t\t<a class=\"dropdown-item\"href=\"SemiProjectServlet.do?command=mypage\"><strong style=\"color:dark;\">My page</strong></a>\r\n");
      out.write("    \t\t</div>\r\n");
      out.write("\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t<!-- 드롭다운 종료 -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<!-- 버튼 -->\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<a class=\"navbar-brand\" href=\"user_main.jsp\">UTC</a>\r\n");
      out.write("\t\t\t<button class=\"navbar-toggler\" type=\"button\" data-toggle=\"collapse\"\r\n");
      out.write("\t\t\t\tdata-target=\"#navbarResponsive\" aria-controls=\"navbarResponsive\"\r\n");
      out.write("\t\t\t\taria-expanded=\"false\" aria-label=\"Toggle navigation\">\r\n");
      out.write("\t\t\t\t<span class=\"navbar-toggler-icon\"></span>\r\n");
      out.write("\t\t\t\t<!-- 화면줄이면 나오는 버튼 -->\r\n");
      out.write("\t\t\t</button>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"collapse navbar-collapse\" id=\"navbarResponsive\">\r\n");
      out.write("\t\t\t\t<ul class=\"navbar-nav ml-auto\">\r\n");
      out.write("\t\t\t\t\t<li class=\"nav-item\"><li class=\"nav-item\"><a class=\"nav-link\" style=\"color: white;\">");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${dto.member_name }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("님 환영합니다!</a></li>\r\n");
      out.write("               <li class=\"nav-item\"><a class=\"nav-link\"\r\n");
      out.write("\t\t\t\t\t\thref=\"SemiProjectServlet.do?command=logout\">Logout</a>\r\n");
      out.write("\t\t\t\t\t</li>\r\n");
      out.write("\t\t\t\t</ul>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal 1 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal3\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\"></div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t<!-- Modal 2 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<!-- loginform.jsp가 연결된다. -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t\r\n");
      out.write("\t<!-- Modal 3 -->\r\n");
      out.write("\t<div class=\"modal fade\" id=\"myModal2\">\r\n");
      out.write("\t\t<div class=\"modal-dialog modal-md\">\r\n");
      out.write("\t\t\t<div class=\"modal-content\">\r\n");
      out.write("\t\t\t\t<!-- signup.jsp 연결(회원정보수정) -->\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\t/** 모달 창이 닫히는 경우의 이벤트 */\r\n");
      out.write("\t\t// \".modal\"로 지정할 경우 : 모든 모달창에 적용됨\r\n");
      out.write("\t\t// \"#아이디\"로 지정할 경우 : 특정 모달 창에 적용\r\n");
      out.write("\t\t$('.modal').on('hidden.bs.modal', function(e) {\r\n");
      out.write("\t\t\t// 모달창 내의 내용을 강제로 지움.\r\n");
      out.write("\t\t\t$(this).removeData('bs.modal');\r\n");
      out.write("\t\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\t\r\n");
      out.write("\r\n");
      out.write("\t<link href=\"css/index_menu.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"dist/jquery.flipster.min.css\" rel=\"stylesheet\">\r\n");
      out.write("\t<link href=\"plugins/ajax/ajax_helper.css\" rel=\"stylesheet\"/>\r\n");
      out.write("\t\r\n");
      out.write("\t<script src=\"js/index.js\"></script>\t\t\t\t\t\r\n");
      out.write("\t<script src=\"dist/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"dist/jquery.flipster.min.js\"></script>   \r\n");
      out.write("\t<script src=\"plugins/handlebars-v4.0.5.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\t\r\n");
      out.write("<!---------------------------------------바디 바디 바디----------------------------------->\r\n");
      out.write("<body>\r\n");
      out.write("<form action=\"index.jsp\" method=\"post\">\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(0).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(1).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(2).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(3).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(4).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(5).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(6).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(7).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(8).getFile_id());
      out.write(" '/>\r\n");
      out.write("\t<input type=\"hidden\" name=\"contentValue\" value='");
      out.print(list.get(9).getFile_id());
      out.write(" '/>\r\n");
      out.write("</form>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"index\">\r\n");
      out.write("\t\r\n");
      out.write("\t\t<header class=\"masthead text-center text-white\">\t\t<!--  헤더      -->\r\n");
      out.write("\t\t\t<div class=\"masthead-content\">\r\n");
      out.write("\t\t\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t\t\t<h1 class=\"masthead-heading mb-0\">UTC</h1>\r\n");
      out.write("\t\t\t\t\t<h2 class=\"masthead-subheading mb-0\">UI TO CODE</h2>\r\n");
      out.write("\t\t\t\t\t<a href=\"aboutUs.jsp\" class=\"btn btn-primary btn-xl rounded-pill mt-5\">Learn More</a>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"bg-circle-1 bg-circle\"></div>\t\t\t<!--  그림 원   -->\r\n");
      out.write("\t\t\t<div class=\"bg-circle-2 bg-circle\"></div>\r\n");
      out.write("\t\t\t<div class=\"bg-circle-3 bg-circle\"></div>\r\n");
      out.write("\t\t\t<div class=\"bg-circle-4 bg-circle\"></div>\r\n");
      out.write("\t\t</header>,\r\n");
      out.write("\r\n");
      out.write("\t<nav class=\"nav2\" style=\"width: 100%;\">\t\t\t\t\t\t<!-- 메뉴바 -->\r\n");
      out.write("\t\t<a href=\"SemiProjectServlet.do?command=make_up_self\"><strong style=\"color:dark;\">Create My Page</strong></a>\r\n");
      out.write("  \t\t<a href=\"SemiProjectServlet.do?command=list\" ><strong style=\"color:dark;\">User Reviews</strong></a>\r\n");
      out.write("  \t\t<a href=\"SemiProjectServlet.do?command=qalist\"><strong style=\"color:dark;\">Q&nbsp;&&nbsp;A Board</strong></a>\r\n");
      out.write("  \t\t<a href=\"SemiProjectServlet.do?command=ntlist\"><strong style=\"color:dark;\">Notice</strong></a>\r\n");
      out.write("\t\t<a href=\"SemiProjectServlet.do?command=mypage\"><strong style=\"color:dark;\">My page</strong></a>\r\n");
      out.write("\t\t<div class=\"nav-underline\"></div>\r\n");
      out.write("\t</nav>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 order-lg-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"p-5\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid rounded-circle\" src=\"img/01.gif\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 order-lg-1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"p-5\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"display-4\">Select the most anticipated site for 2018</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>교육노동부가 선정한 2018년 가장 기대되는 사이트 선정 1위</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"p-5\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid rounded-circle\" src=\"img/02.gif\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6\">\r\n");
      out.write("\t\t\t\t\t<div class=\"p-5\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"display-4\">직관적 사용</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>Drag & Drop 을 통해 화면이 코드로 나타납니다. 이미지를 활용하여 화면을 구성하고,\r\n");
      out.write("\t\t\t\t\t\t 각 이미지가 나타내는 기능 및 총합된 결과물을 html 코드 형태로 변환해 제공합니다.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("\t<section>\r\n");
      out.write("\t\t<div class=\"container\">\r\n");
      out.write("\t\t\t<div class=\"row align-items-center\">\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 order-lg-2\">\r\n");
      out.write("\t\t\t\t\t<div class=\"p-5\">\r\n");
      out.write("\t\t\t\t\t\t<img class=\"img-fluid rounded-circle\" src=\"img/03.jpg\" alt=\"\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t<div class=\"col-lg-6 order-lg-1\">\r\n");
      out.write("\t\t\t\t\t<div class=\"p-5\">\r\n");
      out.write("\t\t\t\t\t\t<h2 class=\"display-4\">간편한 관리</h2>\r\n");
      out.write("\t\t\t\t\t\t<p>작업물을 임시 저장, 수정, html파일로 저장하여 보관할 수 있습니다. \r\n");
      out.write("\t\t\t\t\t\t다른 사람들과 작업 내용을 공유해 보세요.</p>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</section>\r\n");
      out.write("\r\n");
      out.write("<br>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<article id=\"demo-default\" class=\"demo\">\t\t\t\t\t<!-- 슬라이더 -->\r\n");
      out.write("\t<br><h2 style=\"text-align: center;\">User Reviews</h2><br><br><br><br>\r\n");
      out.write("    <div id=\"coverflow\">\r\n");
      out.write("        <ul class=\"flip-items\">\r\n");
      out.write("            <li data-flip-title=\"Red\">\r\n");
      out.write("                <iframe class=\"myFrame0\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Razzmatazz\" data-flip-category=\"Purples\">\r\n");
      out.write("                <iframe class=\"myFrame1\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("             </li>\r\n");
      out.write("            <li data-flip-title=\"Deep Lilac\" data-flip-category=\"Purples\">\r\n");
      out.write("                <iframe class=\"myFrame2\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Daisy Bush\" data-flip-category=\"Purples\">\r\n");
      out.write("                <iframe class=\"myFrame3\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Cerulean Blue\" data-flip-category=\"Blues\">\r\n");
      out.write("                <iframe class=\"myFrame4\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Dodger Blue\" data-flip-category=\"Blues\">\r\n");
      out.write("                <iframe class=\"myFrame5\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Cyan\" data-flip-category=\"Blues\">\r\n");
      out.write("                <iframe class=\"myFrame6\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Robin's Egg\" data-flip-category=\"Blues\">\r\n");
      out.write("                <iframe class=\"myFrame7\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Deep Sea\" data-flip-category=\"Greens\">\r\n");
      out.write("                <iframe class=\"myFrame8\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li data-flip-title=\"Apple\" data-flip-category=\"Greens\">\r\n");
      out.write("                <iframe class=\"myFrame9\" style=\"height: 500px; width: 500px;\" src=\"\"></iframe>\r\n");
      out.write("            </li>\r\n");
      out.write("        </ul>\r\n");
      out.write("    </div>\r\n");
      out.write("\t\t<script type=\"text/javascript\">\r\n");
      out.write("    \t\tvar coverflow = $(\"#coverflow\").flipster();\r\n");
      out.write("\t\t</script>\r\n");
      out.write("</article>\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write('\r');
      out.write('\n');
 request.setCharacterEncoding("UTF-8"); 
      out.write('\r');
      out.write('\n');
 response.setContentType("text/html; charset=UTF-8"); 
      out.write("    \r\n");
      out.write("    \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>footer</title>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write(".footer{\r\n");
      out.write("\r\n");
      out.write("left: 0;\r\n");
      out.write("bottom: 10px;\r\n");
      out.write("width: 100%;\r\n");
      out.write("background-color: black;\r\n");
      out.write("opacity: 0.8;\r\n");
      out.write("color: silver;\r\n");
      out.write("text-align: center;\r\n");
      out.write("font-size: small;\r\n");
      out.write("#4c4c4c; \r\n");
      out.write("height: 100px;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("      <div class=\"footer\">\r\n");
      out.write("         <p>Copyright &copy; ;&nbsp;&nbsp;&nbsp;Website 2018</p>\r\n");
      out.write("         <p>제작자 : 김동민 박우주 성원실 전성은 최강일 최경수</p>\r\n");
      out.write("         <p>제작 일자&nbsp; 2018-12-12</p>\r\n");
      out.write("      </div>\r\n");
      out.write("   \r\n");
      out.write("   <!-- Bootstrap core JavaScript -->\r\n");
      out.write("   <script src=\"vendor/jquery/jquery.min.js\"></script>\r\n");
      out.write("   <script src=\"vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
